var tableauQuestion = [
    {   question : "ใบอนุญาตขับรถส่วนบุคคลชั่วคราวมีอายุกี่ปี",
        propositionA : "1 ปี",
        propositionB : "2 ปี",
        propositionC : "3 ปี",
        propositionD : "5 ปี",
        reponse : "A"},

    {   question : "ผู้ขับขี่ต้องการเลี้ยวขวาและมีรถทางตรงวิ่งสวนมา จะต้องปฏิบัติอย่างไร",
        propositionA : "หยุดรถให้รถทางขวามือผ่านไปก่อนจึงเลี้ยวขวาได้",
        propositionB : "หยุดรอให้รถทางตรงสวนมาก่อนจึงเลี้ยวขวาได้",
        propositionC : "เลี้ยวได้ทันที",
        propositionD : "ห้ามเลี้ยวรถ",
        reponse : "B"},

    {   question : "กรณีมีรถเลี้ยวซ้ายและเลี้ยวขวาพร้อมกันในเส้นทางเดียวกันผู้ขับขี่ต้องทำอย่างไร",
        propositionA : "ผู้ที่จะเลี้ยวซ้ายเลี้ยวได้ทันที",
        propositionB : "ผู้ที่จะเลี้ยวซ้ายต้องหยุดให้ทางแก่รถที่เลี้ยวมาจากทางขวาก่อน",
        propositionC : "ผู้ที่จะเลี้ยวขวาต้องหยุดให้ทางแก่รถที่เลี้ยวมาจากทางด้านซ้ายก่อน",
        propositionD : "ห้ามเลี้ยวซ้าย",
        reponse : "B"},

  {   question : "ก่อนเปลี่ยนเลนทุกครั้งคุณต้อง:",
        propositionA : "มองกระจกข้าง",
        propositionB : "ตรวจสอบจุดบอดของคุณ",
        propositionC : "เช็คให้รอบคอบ",
        propositionD : "ทุกข้อที่กล่าวมา",
        reponse : "D"},

  {   question : "ระดับแอลกอฮอล์ในเลือดกี่เปอร์เซ็นถูกจัดอยู่ในประเภทเมาแล้วขับ?",
        propositionA : "0.05%",
        propositionB : "0.18%",
        propositionC : "0.08%",
        propositionD : "0.06%",
        reponse : "C"},

  {   question : "คุณสามารถขับรถต่อไปได้เมื่อเห็นไฟจราจรเป็นสีอะไร?",
        propositionA : "สีเหลือง",
        propositionB : "เมื่อไม่มีใครอยู่ในสี่แยก",
        propositionC : "เมื่อคุณอยู่ในเขตโรงเรียน",
        propositionD : "สีเขียว",
        reponse : "D"},

  {   question : "กรณีที่เราเห็นรถคันอื่นให้สัญญาณจะเลี้ยวรถหรือเปลี่ยนช่องทางการเดินรถ จะต้องปฏิบัติอย่างไร?",
        propositionA : "หยุดรถ",
        propositionB : "จอดรถ",
        propositionC : "ชะลอความเร็วและให้ทางแก่เขาไปก่อน",
        propositionD : "เร่งความเร็วเพื่อจะไปก่อน",
        reponse : "C"},

  {   question : "การขับรถขณะฝนตก.ข้อใดที่ผู้ขับขี่ไม่ควรปฏิบัติ",
        propositionA : "เปิดไฟฉุกเฉินตลอดเส้นทาง",
        propositionB : "เปิดที่ปัดน้ำฝน",
        propositionC : "ใช้ความระมัดระวังเพิ่มมากขึ้น",
        propositionD : "ลดความเร็วของรถลงกว่าปกติ",
        reponse : "A"},

  {   question : "คุณกำลังขับรถบนทางหลวงซึ่งระบุว่ามีความเร็วสูงสุด 70 ไมล์ต่อชั่วโมง การจราจรส่วนใหญ่ขับที่ 75 ไมล์ดังนั้นคุณจึงไม่ควรขับรถเร็วกว่า:",
        propositionA : "50 mph",
        propositionB : "25 mph",
        propositionC : "30 mph",
        propositionD : "70 mph",
        reponse : "D"},

  {   question : "เมื่อคุณถูกแซง สิ่งสำคัญที่คุณจะต้องไม่ทำเลยคือ",
        propositionA : "ลดความเร็ว",
        propositionB : "เช็คกระจก",
        propositionC : "ดูคนขับคนอื่น",
        propositionD : "เพิ่มความเร็ว",
        reponse : "D"},
]
