Config = {}

Config.Animations = {

	{
		name  = 'festives',
		label = 'ท่าทาง',
		items = {
			{label = "สูบบุหรี่", type = "scenario", data = {anim = "WORLD_HUMAN_SMOKING"}},
			{label = "เล่นเพลง", type = "scenario", data = {anim = "WORLD_HUMAN_MUSICIAN"}},
			{label = "ดีเจ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@dj", anim = "dj"}},
			{label = "ดื่มเบียร์", type = "scenario", data = {anim = "WORLD_HUMAN_DRINKING"}},
			{label = "ปาร์ตี้", type = "scenario", data = {anim = "WORLD_HUMAN_PARTYING"}},
			{label = "ดีดกีตาร์อากาศ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@air_guitar", anim = "air_guitar"}},
			{label = "เด้ากลางอากาศ", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@air_shagging", anim = "air_shagging"}},
			{label = "ร็อค & โรล", type = "anim", data = {lib = "mp_player_int_upperrock", anim = "mp_player_int_rock"}},
		}
	},


	{
		name  = 'faceemote',
		label = 'อารมณ์ใบหน้า',
		items = {
			{label = "ปกติ", type = "face", data = {anim = "mood_normal_1"}},
			{label = "พอใจ", type = "face", data = {anim = "mood_smug_1"}},
			{label = "เครียด", type = "face", data = {anim = "mood_stressed_1"}},
			{label = "ขับรถเร็ว", type = "face", data = {anim = "mood_drivefast_1"}},
			{label = "Skydive", type = "face", data = {anim = "mood_skydive_1"}},
			{label = "เจ็บ", type = "face", data = {anim = "mood_injured_1"}},
			{label = "โกรธ", type = "face", data = {anim = "mood_angry_1"}},
			{label = "เมา", type = "face", data = {anim = "mood_drunk_1"}},
			{label = "มีความสุข", type = "face", data = {anim = "mood_happy_1"}},
			{label = "เคืองใจ", type = "face", data = {anim = "mood_sulk_1"}},
			{label = "เล็ง", type = "face", data = {anim = "mood_aiming_1"}},
			{label = "ผวา 1", type = "face", data = {anim = "shocked_1"}},
			{label = "ผวา 2", type = "face", data = {anim = "shocked_2"}},
			{label = "ร้อน", type = "face", data = {anim = "burning_1"}},
			{label = "ไอ", type = "face", data = {anim = "coughing"}},
			{label = "ความพยายาม (ต่ำ)", type = "face", data = {anim = "effort_1"}},
			{label = "ความพยายาม (กลาง)", type = "face", data = {anim = "effort_2"}},
			{label = "ความพยายาม (สูง)", type = "face", data = {anim = "effort_3"}},
			{label = "ไฟดูด", type = "face", data = {anim = "electrocuted_1"}},
			{label = "เจ็บปวด", type = "face", data = {anim = "pain_6"}},
			{label = "หลับตา", type = "face", data = {anim = "mood_sleeping_1"}},
		}
	},

	{
		name  = 'attitudem',
		label = 'ท่าเดิน',
		items = {
			{label = "Normal M", type = "attitude", data = {lib = "move_m@confident", anim = "move_m@confident"}},
			{label = "Normal F", type = "attitude", data = {lib = "move_f@heels@c", anim = "move_f@heels@c"}},
			{label = "Depressif", type = "attitude", data = {lib = "move_m@depressed@a", anim = "move_m@depressed@a"}},
			{label = "Depressif F", type = "attitude", data = {lib = "move_f@depressed@a", anim = "move_f@depressed@a"}},
			{label = "นักธุรกิจ", type = "attitude", data = {lib = "move_m@business@a", anim = "move_m@business@a"}},
			{label = "นักเลง", type = "attitude", data = {lib = "move_m@brave@a", anim = "move_m@brave@a"}},
			{label = "ตามอารมณ์", type = "attitude", data = {lib = "move_m@casual@a", anim = "move_m@casual@a"}},
			{label = "แน่ท้อง", type = "attitude", data = {lib = "move_m@fat@a", anim = "move_m@fat@a"}},
			{label = "ฮิปสเตอร์", type = "attitude", data = {lib = "move_m@hipster@a", anim = "move_m@hipster@a"}},
			{label = "กุ๊ย", type = "attitude", data = {lib = "move_m@hobo@a", anim = "move_m@hobo@a"}},
			{label = "เศร้า", type = "attitude", data = {lib = "move_m@sad@a", anim = "move_m@sad@a"}},
			{label = "นักกล้าม", type = "attitude", data = {lib = "move_m@muscle@a", anim = "move_m@muscle@a"}},
			{label = "มองท้องฟ้า", type = "attitude", data = {lib = "move_m@shadyped@a", anim = "move_m@shadyped@a"}},
			{label = "เมื่อยล้า", type = "attitude", data = {lib = "move_m@buzzed", anim = "move_m@buzzed"}},
			{label = "มองหน้า", type = "attitude", data = {lib = "move_m@hurry_butch@a", anim = "move_m@hurry_butch@a"}},
			{label = "เดินแบบกวนๆ", type = "attitude", data = {lib = "move_m@money", anim = "move_m@money"}},
			{label = "อ่อย", type = "attitude", data = {lib = "move_f@maneater", anim = "move_f@maneater"}},
			{label = "หน้าด้าน", type = "attitude", data = {lib = "move_f@sassy", anim = "move_f@sassy"}},	
			{label = "หยิ่ง", type = "attitude", data = {lib = "move_f@arrogant@a", anim = "move_f@arrogant@a"}},
		}
	},

	{
		name  = 'greetings',
		label = 'ทักทาย',
		items = {
			{label = "ทักทาย", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_hello"}},
			{label = "จับมือ", type = "anim", data = {lib = "mp_common", anim = "givetake1_a"}},
			{label = "จับมือ 2", type = "anim", data = {lib = "mp_ped_interaction", anim = "handshake_guy_a"}},
			{label = "นักเลง", type = "anim", data = {lib = "mp_ped_interaction", anim = "hugs_guy_a"}},
			{label = "ตำรวจ", type = "anim", data = {lib = "mp_player_int_uppersalute", anim = "mp_player_int_salute"}},
		}
	},

	{
		name  = 'work',
		label = 'ทำงาน',
		items = {
			{label = "จดบันทึก", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_TIME_OF_DEATH"}},
			{label = "Cop Idle", type = "scenario", data = {anim = "WORLD_HUMAN_COP_IDLES"}},
			{label = "โดนจับคุม", type = "anim", data = {lib = "random@arrests@busted", anim = "idle_c"}},
			{label = "ตกปลา", type = "scenario", data = {anim = "world_human_stand_fishing"}},
			{label = "สอบสวน", type = "anim", data = {lib = "amb@code_human_police_investigate@idle_b", anim = "idle_f"}},
			{label = "วิทยุสื่อสาร", type = "anim", data = {lib = "random@arrests", anim = "generic_radio_chatter"}},
			{label = "โบกรถ", type = "scenario", data = {anim = "WORLD_HUMAN_CAR_PARK_ATTENDANT"}},
			{label = "เก็บเกี่ยว", type = "scenario", data = {anim = "world_human_gardener_plant"}},
			{label = "ซ่อมเครื่องยนต์", type = "anim", data = {lib = "mini@repair", anim = "fixing_a_ped"}},
			{label = "สังเกต", type = "scenario", data = {anim = "CODE_HUMAN_MEDIC_KNEEL"}},
			{label = "ช็อปปิ้ง", type = "anim", data = {lib = "mp_am_hold_up", anim = "purchase_beerbox_shopkeeper"}},
			{label = "ใส่กระสุนปืนใหญ่", type = "anim", data = {lib = "mini@drinking", anim = "shots_barman_b"}},
			{label = "ถ่ายรูป", type = "scenario", data = {anim = "WORLD_HUMAN_PAPARAZZI"}},
			{label = "จดบันทึก", type = "scenario", data = {anim = "WORLD_HUMAN_CLIPBOARD"}},
			{label = "ใช้ค้อนตี", type = "scenario", data = {anim = "WORLD_HUMAN_HAMMERING"}},
			{label = "ถือป้าย", type = "scenario", data = {anim = "WORLD_HUMAN_BUM_FREEWAY"}},
			{label = "ทำรูปปั้น", type = "scenario", data = {anim = "WORLD_HUMAN_HUMAN_STATUE"}},
			{label = "โฮสเตอร์", type = "scenario", data = {anim = "CODE_HUMAN_POLICE_INVESTIGATE"}},
		}
	},

	{
		name  = 'humors',
		label = 'ตลก',
		items = {
			{label = "แสดงความยินดี", type = "scenario", data = {anim = "WORLD_HUMAN_CHEERING"}},
			{label = "ขำขันมาก", type = "anim", data = {lib = "mp_action", anim = "thanks_male_06"}},
			{label = "ขำขัน", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_point"}},
			{label = "อารมณ์ขันมา", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_come_here_soft"}}, 
			{label = "ลีลาศ", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_bring_it_on"}},
			{label = "สำหรับฉัน", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_me"}},
			{label = "ฉันรู้ว่ามันเป็นร่วมเพศ", type = "anim", data = {lib = "anim@am_hold_up@male", anim = "shoplift_high"}},		
			{label = "กุมขมับ", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@face_palm", anim = "face_palm"}},
			{label = "สงบสติอารมณ์ ", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_easy_now"}},
			{label = "ฉันทำอะไร?", type = "anim", data = {lib = "oddjobs@assassinate@multi@", anim = "react_big_variations_a"}},
			{label = "ต้องกลัว", type = "anim", data = {lib = "amb@code_human_cower_stand@male@react_cowering", anim = "base_right"}},
			{label = "ต่อสู้?", type = "anim", data = {lib = "anim@deathmatch_intros@unarmed", anim = "intro_male_unarmed_e"}},
			{label = "ไม่สามารถทำได้ !", type = "anim", data = {lib = "gestures@m@standing@casual", anim = "gesture_damn"}},
			{label = "โอบกอด", type = "anim", data = {lib = "mp_ped_interaction", anim = "kisses_guy_a"}},
			{label = "เกียรติยศ", type = "anim", data = {lib = "mp_player_int_upperfinger", anim = "mp_player_int_finger_01_enter"}},
			{label = "โรคจิต", type = "anim", data = {lib = "mp_player_int_upperwank", anim = "mp_player_int_wank_01"}},
			{label = "บอลในหัว", type = "anim", data = {lib = "mp_suicide", anim = "pistol"}},
		}
	},

	{
		name  = 'sports',
		label = 'กีฬา',
		items = {
			{label = "โชว์กล้าม", type = "anim", data = {lib = "amb@world_human_muscle_flex@arms_at_side@base", anim = "base"}},
			{label = "แถบน้ำหนัก", type = "anim", data = {lib = "amb@world_human_muscle_free_weights@male@barbell@base", anim = "base"}},
			{label = "วิดฟื้น", type = "anim", data = {lib = "amb@world_human_push_ups@male@base", anim = "base"}},
			{label = "ซิทอัพ", type = "anim", data = {lib = "amb@world_human_sit_ups@male@base", anim = "base"}},
			{label = "ทำโยคะ", type = "anim", data = {lib = "amb@world_human_yoga@male@base", anim = "base_a"}},
		}
	},

	{
		name  = 'misc',
		label = 'อื่นๆ',
		items = {
			{label = "ดื่มกาแฟ", type = "anim", data = {lib = "amb@world_human_aa_coffee@idle_a", anim = "idle_a"}},
			{label = "นั่ง", type = "anim", data = {lib = "anim@heists@prison_heistunfinished_biztarget_idle", anim = "target_idle"}},
			{label = "นอนอยู่ด้านหลัง", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE_BACK"}},
			{label = "นอนอยู่บนท้อง", type = "scenario", data = {anim = "WORLD_HUMAN_SUNBATHE"}},
			{label = "ทำความสะอาดบางสิ่งบางอย่าง", type = "scenario", data = {anim = "world_human_maid_clean"}},
			{label = "เตรียมที่จะกิน", type = "scenario", data = {anim = "PROP_HUMAN_BBQ"}},			
			{label = "เซฟฟี่", type = "scenario", data = {anim = "world_human_tourist_mobile"}},
			{label = "ฟังประตู", type = "anim", data = {lib = "mini@safe_cracking", anim = "idle_base"}}, 
			{label = "นั่งบนพื้น", type = "scenario", data = {anim = "WORLD_HUMAN_PICNIC"}},
			{label = "ใจร้อน", type = "scenario", data = {anim = "WORLD_HUMAN_STAND_IMPATIENT"}},
			{label = "มึนงง", type = "scenario", data = {anim = "WORLD_HUMAN_STUPOR"}},
			{label = "รอใครบางคน", type = "scenario", data = {anim = "CODE_HUMAN_CROSS_ROAD_WAIT"}},
		}
	},
	{
		name  = 'porn',
		label = 'ลามก',
		items = {			
			{label = "เกาหำ", type = "anim", data = {lib = "mp_player_int_uppergrab_crotch", anim = "mp_player_int_grab_crotch"}},
			{label = "อ่อย", type = "anim", data = {lib = "mini@strip_club@idles@stripper", anim = "stripper_idle_02"}},
			{label = "อ่อย 2", type = "scenario", data = {anim = "WORLD_HUMAN_PROSTITUTE_HIGH_CLASS"}},
			{label = "โชว์หน้าอก", type = "anim", data = {lib = "mini@strip_club@backroom@", anim = "stripper_b_backroom_idle_b"}},
			{label = "เซ็กซี่ 1", type = "anim", data = {lib = "mini@strip_club@lap_dance@ld_girl_a_song_a_p1", anim = "ld_girl_a_song_a_p1_f"}},
			{label = "เซ็กซี่ 2", type = "anim", data = {lib = "mini@strip_club@private_dance@part2", anim = "priv_dance_p2"}},
			{label = "ให้ท่า", type = "anim", data = {lib = "mini@strip_club@private_dance@part3", anim = "priv_dance_p3"}},
			{label = "เกาะบาร์", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@", anim = "li-mi_amb_club_06_base_male^1"}},
            {label = "เกาะบาร์ชนแก้ว", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@", anim = "li-mi_amb_club_13_v1_male^6"}},
            {label = "เกาะบาร์โยก", type = "anim", data = {lib = "anim@amb@nightclub@dancers@club_ambientpeds@med-hi_intensity", anim = "mi-hi_amb_club_10_v1_male^6"}},
            {label = "เคาะประตู", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@ds@base", anim = "idle_a_fp"}},
            {label = "โยกเบาๆ", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@bodhi@rds@base", anim = "idle_b"}},
            {label = "โยกเล็กน้อย", type = "anim", data = {lib = "amb@code_human_in_car_mp_actions@dance@std@ds@base", anim = "idle_a"}},
            {label = "โยกแรงๆ", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", anim = "hi_dance_facedj_09_v2_male^6"}},
            {label = "โยกทั้งตัว", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_low_intensity", anim = "trans_dance_facedj_li_to_hi_07_v1_male^6"}},
            {label = "โยกขยับแขน", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_13_v2_male^6"}},        
            {label = "เมา", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props_transitions@from_med_intensity", anim = "trans_crowd_prop_mi_to_li_11_v1_male^6"}},
            {label = "โยกแบบมวย", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_center_up"}},
            {label = "โยกแบบมวย 2", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", anim = "med_right_up"}},
            {label = "โยกในผับ", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@low_intensity", anim = "li_dance_crowd_17_v1_male^6"}},
            {label = "โยกในผับ 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_med_intensity", anim = "trans_dance_facedj_mi_to_li_09_v1_male^6"}},
            {label = "กระเป๋าตังหาย", type = "anim", data = {lib = "special_ped@zombie@monologue_4@monologue_4l", anim = "iamtheundead_11"}},
            {label = "นกกระยาง", type = "anim", data = {lib = "timetable@tracy@ig_5@idle_b", anim = "idle_e"}},
            {label = "ว่ายน้ำ", type = "anim", data = {lib = "mini@strip_club@idles@dj@idle_04", anim = "idle_04"}},
            {label = "มดกัดตีน 1", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_1@monologue_1a", anim = "mtn_dnc_if_you_want_to_get_to_heaven"}},
            {label = "มดกัดตีน 2", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_4@monologue_4a", anim = "mnt_dnc_verse"}},
            {label = "มดกัดตีน 3", type = "anim", data = {lib = "special_ped@mountain_dancer@monologue_3@monologue_3a", anim = "mnt_dnc_buttwag"}},
            {label = "วอร์มเครื่อง 1", type = "anim", data = {lib = "anim@amb@nightclub@dancers@black_madonna_entourage@", anim = "hi_dance_facedj_09_v2_male^5"}},
            {label = "วอร์มเครื่อง 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_single_props@", anim = "hi_dance_prop_09_v1_male^6"}},
            {label = "วอร์มเครื่อง 3", type = "anim", data = {lib = "anim@amb@nightclub@dancers@dixon_entourage@", anim = "mi_dance_facedj_15_v1_male^4"}},
            {label = "วอร์มเครื่อง 4", type = "anim", data = {lib = "anim@amb@nightclub@dancers@podium_dancers@", anim = "hi_dance_facedj_17_v2_male^5"}},
            {label = "วอร์มเครื่อง 5", type = "anim", data = {lib = "anim@amb@nightclub@dancers@tale_of_us_entourage@", anim = "mi_dance_prop_13_v2_male^4"}},
            {label = "รำไทย", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_cs", anim = "dance_loop_tao"}},
            {label = "รำไทย 2", type = "anim", data = {lib = "misschinese2_crystalmazemcs1_ig", anim = "dance_loop_tao"}},
            {label = "หมัดเชิงมวย", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@uncle_disco", anim = "uncle_disco"}},
            {label = "Push your handsup", type = "anim", data = {lib = "anim@mp_player_intcelebrationfemale@raise_the_roof", anim = "raise_the_roof"}},
            {label = "กระหัง", type = "anim", data = {lib = "anim@mp_player_intcelebrationmale@cats_cradle", anim = "cats_cradle"}},
            {label = "ยกสุดมือ", type = "anim", data = {lib = "anim@mp_player_intupperbanging_tunes", anim = "idle_a"}},
			{label = "ส่ายหนัก", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", anim = "high_center"}},
			{label = "ส่ายหนัก 2", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", anim = "high_center"}},
			{label = "ท่าเด็กช่าง", type = "anim", data = {lib = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", anim = "high_center"}},
			{label = "นารีทัดหู", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@", anim = "trans_dance_facedj_hi_to_mi_11_v1_female^6"}},
			{label = "นารีวอร์มเครื่อง", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj_transitions@from_hi_intensity", anim = "trans_dance_facedj_hi_to_li_07_v1_female^6"}},
			{label = "นารีวอร์มเครื่อง 2", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_facedj@", anim = "hi_dance_facedj_09_v1_female^6"}},
			{label = "นารีวอร์มเครื่อง 3", type = "anim", data = {lib = "anim@amb@nightclub@dancers@crowddance_groups@hi_intensity", anim = "hi_dance_crowd_09_v1_female^6"}},
			{label = "นารีตั้งท่า", type = "anim", data = {lib = "anim@amb@nightclub@lazlow@hi_podium@", anim = "danceidle_hi_06_base_laz"}},
		}
	}
}